variables:
  PYTHON_VERSION: "3.12"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  SERVICE_NAME: "recommendationservice"

stages:
  - build
  - test
  - security
  - sonar
  - package
  - update-helm
  - deploy_pipeline

.python_cache: &python_cache
  cache:
    key: "${CI_COMMIT_REF_SLUG}-python"
    paths:
      - .venv/

build:
  stage: build
  image: python:${PYTHON_VERSION}-alpine
  <<: *python_cache
  before_script:
    - apk add --no-cache gcc g++ musl-dev linux-headers python3-dev
    - python -m venv .venv
    - source .venv/bin/activate
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  artifacts:
    paths:
      - .venv/
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test:
  stage: test
  image: python:${PYTHON_VERSION}-alpine
  needs:
    - build
  <<: *python_cache
  before_script:
    - source .venv/bin/activate
  script:
    - |
      if python -m pytest --version >/dev/null 2>&1; then
        python -m pytest
      else
        echo "No tests configured or pytest not installed"
        echo "Skipping test execution for now"
      fi
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

security:
  stage: security
  image: python:${PYTHON_VERSION}-alpine
  needs:
    - build
  <<: *python_cache
  before_script:
    - apk add --no-cache gcc g++ musl-dev linux-headers python3-dev
    - source .venv/bin/activate
    - pip install safety
  script:
    - safety scan --output json > safety-report.json || echo "Security vulnerabilities found but continuing..."
  artifacts:
    reports:
      sast: safety-report.json
    paths:
      - safety-report.json
    expire_in: 1 week
    when: always
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

sonar:
  stage: sonar
  image: python:${PYTHON_VERSION}
  <<: *python_cache
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  before_script:
    - apt-get update && apt-get install -y openjdk-21-jre-headless wget unzip
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.2.1.4610-linux-x64.zip
    - unzip sonar-scanner-cli-6.2.1.4610-linux-x64.zip
    - export PATH="$PATH:$(pwd)/sonar-scanner-6.2.1.4610-linux-x64/bin"
  script:
    - >
      sonar-scanner
      -Dsonar.projectKey="seunayolu_gitops-recommendationservice"
      -Dsonar.organization="${SONAR_ORGANIZATION}"
      -Dsonar.host.url="${SONAR_HOST_URL}"
      -Dsonar.token="${SONAR_TOKEN}"
      -Dsonar.sources=.
      -Dsonar.exclusions=".venv/**,__pycache__/**"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

package:
  stage: package
  image: docker:28.3.3
  needs:
    - sonar
  tags:
    - ec2_2
  services:
    - docker:28.3.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_BUILDKIT: 1 
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - >
      docker buildx build
      --cache-to type=inline
      --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/${SERVICE_NAME}:latest
      -t $CI_REGISTRY_IMAGE/${SERVICE_NAME}:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY_IMAGE/${SERVICE_NAME}:latest
      -f Dockerfile
      --push .    
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    
update-helm-values:
  stage: update-helm
  image: alpine:latest
  needs:
    - package
  before_script:
    - apk add --no-cache git yq
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
  script:
    - git clone https://gitlab-ci-token:${HELM_REPO_TOKEN}@${HELM_REPO_URL#https://} helm-repo
    - cd helm-repo/microservices-chart
    - git checkout feature/boutique-helm
    - yq eval ".services.${SERVICE_NAME}.image.repository = \"$CI_REGISTRY_IMAGE/${SERVICE_NAME}\"" -i values.yaml
    - yq eval ".services.${SERVICE_NAME}.image.tag = \"$CI_COMMIT_SHORT_SHA\"" -i values.yaml
    - git add values.yaml
    - git commit -m "Update ${SERVICE_NAME} image to ${CI_COMMIT_SHORT_SHA}"
    - git push origin feature/boutique-helm
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

trigger_deploy_pipeline:
  stage: deploy_pipeline
  needs:
    - update-helm-values
  trigger:
    project: seunayolu/gitops-helm
    branch: feature/boutique-helm
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == "main"