apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      serviceAccountName: paymentservice
      terminationGracePeriodSeconds: 5
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
      - name: server
        securityContext:
          {{- toYaml .Values.containerSecurityContext | nindent 10 }}
        image: {{ .Values.services.paymentservice.image.repository }}:{{ .Values.services.paymentservice.image.tag }}
        ports:
        - containerPort: {{ .Values.services.paymentservice.port }}
        env:
        - name: PORT
          value: "{{ .Values.services.paymentservice.port }}"
        - name: DISABLE_PROFILER
          value: "1"
        readinessProbe:
          grpc:
            port: {{ .Values.services.paymentservice.port }}
        livenessProbe:
          grpc:
            port: {{ .Values.services.paymentservice.port }}
        resources:
          {{- toYaml .Values.services.paymentservice.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  labels:
    app: paymentservice
spec:
  type: ClusterIP
  selector:
    app: paymentservice
  ports:
  - name: grpc
    port: {{ .Values.services.paymentservice.port }}
    targetPort: {{ .Values.services.paymentservice.port }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice