variables:
  GO_VERSION: "1.23"
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  SERVICE_NAME: "checkoutservice"

stages:
  - build
  - test
  - sonar
  - package
  - update-helm
  - deploy_pipeline

.go_cache: &go_cache
  cache:
    key: "${CI_COMMIT_REF_SLUG}-go"
    paths:
      - .go/pkg/mod/

build:
  stage: build
  image: golang:${GO_VERSION}
  <<: *go_cache
  variables:
    GOMODCACHE: ${CI_PROJECT_DIR}/.go/pkg/mod
  script:
    - go mod download
    - go build -o checkoutservice
  artifacts:
    paths:
      - checkoutservice
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

test:
  stage: test
  image: golang:${GO_VERSION}
  needs:
    - build
  <<: *go_cache
  variables:
    GOMODCACHE: ${CI_PROJECT_DIR}/.go/pkg/mod
  script:
    - go mod download
    - go test -v ./...
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

sonar:
  stage: sonar
  image: golang:${GO_VERSION}
  needs:
    - test
  <<: *go_cache
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  before_script:
    - apt-get update && apt-get install -y openjdk-17-jre-headless wget unzip
    - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
    - unzip sonar-scanner-cli-5.0.1.3006-linux.zip
    - export PATH="$PATH:$(pwd)/sonar-scanner-5.0.1.3006-linux/bin"
  script:
    - >
      sonar-scanner
      -Dsonar.projectKey="seunayolu_gitops-checkoutservice"
      -Dsonar.organization="${SONAR_ORGANIZATION}"
      -Dsonar.host.url="${SONAR_HOST_URL}"
      -Dsonar.token="${SONAR_TOKEN}"
      -Dsonar.sources=.
      -Dsonar.exclusions="vendor/**"
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

package:
  stage: package
  image: docker:28.3.3
  needs:
    - sonar
  tags:
    - ec2_2
  services:
    - docker:28.3.3-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_BUILDKIT: 1 
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - >
      docker buildx build
      --cache-to type=inline
      --cache-from type=registry,ref=$CI_REGISTRY_IMAGE/${SERVICE_NAME}:$CI_COMMIT_SHORT_SHA
      -t $CI_REGISTRY_IMAGE/${SERVICE_NAME}:$CI_COMMIT_SHORT_SHA
      -f Dockerfile
      --push .    
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    
update-helm-values:
  stage: update-helm
  image: alpine:latest
  needs:
    - package
  before_script:
    - apk add --no-cache git yq
    - git config --global user.email "ci@gitlab.com"
    - git config --global user.name "GitLab CI"
  script:
    - git clone https://gitlab-ci-token:${HELM_REPO_TOKEN}@${HELM_REPO_URL#https://} helm-repo
    - cd helm-repo/microservices-chart
    - git checkout feature/boutique-helm
    - yq eval ".services.${SERVICE_NAME}.image.repository = \"$CI_REGISTRY_IMAGE/${SERVICE_NAME}\"" -i values.yaml
    - yq eval ".services.${SERVICE_NAME}.image.tag = \"$CI_COMMIT_SHORT_SHA\"" -i values.yaml
    - git add values.yaml
    - git commit -m "Update ${SERVICE_NAME} image to ${CI_COMMIT_SHORT_SHA}"
    - git push origin feature/boutique-helm
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

trigger_deploy_pipeline:
  stage: deploy_pipeline
  needs:
    - update-helm-values
  trigger:
    project: seunayolu/gitops-helm
    branch: feature/boutique-helm
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == "main"