name: BUILD SCAN PUSH AND UPDATE IMAGE FOR ADSERVICE

on:
  push:
    branches:
      - main
    paths:
      - 'adservice/**'
      - '.github/workflows/ad.yaml'
jobs:
  call-build-scan-and-push-adservice-image:
    uses: ./.github/workflows/reuseable-build-docker-image.yaml
    with:
      image_name: adservice
      dockerfile_path: adservice/Dockerfile
      context_path: adservice
      tag: ${{ github.run_id }}
      trivy_severity: 'CRITICAL,HIGH'
    secrets:
      GHCR_TOKEN: ${{ secrets.TOKEN }}

