name: BUILD PUSH SCAN AND UPDATE IMAGE FOR AD SERVICE

on:
  push:
    branches:
      - main
    paths:
      - 'adservice/**'
      - '.github/workflows/ad.yaml'
jobs:
  call-build-push-and-scan-cartservice-image:
    uses: ./.github/workflows/build-docker-image.yaml
    with:
      image_name: ad
      dockerfile_path: adservice/Dockerfile
      context_path: adservice
      tag: ${{ github.run_id }}
      trivy_severity: 'CRITICAL,HIGH'
    secrets:
      GHCR_TOKEN: ${{ secrets.TOKEN }}

  echo-job:
    runs-on: ubuntu-latest
    needs: call-build-push-and-scan-cartservice-image
    steps:
      - name: Echo job completion
        run: echo "Build, push, and scan for ad service completed."