name: BUILD PUSH AND UPDATE TAG

on:
  push:
    branches:
      - main
    paths:
      - 'checkoutservice/**'
      - '.github/workflows/checkout.yaml'

jobs:
  
  build-and-push:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GCR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Build and Push Image
      uses: docker/build-push-action@v6
      with:
        context: checkoutservice
        file: ./Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.repository }}/ads:${{ github.run_id }}

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: "${{ env.REGISTRY }}/${{ github.repository }}/ads:${{ github.run_id }}"
        format: "sarif"
        security-checks: "vuln,config,secret"
        exit-code: 0
        output: "trivy-report.sarif"
        ignore-unfixed: true
        severity: "CRITICAL,HIGH"

  # update-tag-in-helm-chart:
  #   runs-on: ubuntu-latest

  #   needs: build-and-push

  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v4
  #     with:
  #       token: ${{ secrets.TOKEN }}

  #   - name: Update tag in Helm chart
  #     run: |
  #       sed -i 's/tag: .*/tag: "${{github.run_id}}"/' ./online-boutique/helm/microservices-chart/values.yaml

  #   - name: login to github
  #     run: |
  #        git config --global user.email "amadidominic15@gmail.com"
  #        git config --global user.name "Amadidominic15"

  #   - name: Commit and push changes
  #     run: |
  #       git add .online-boutique/helm/microservices-chart/values.yaml
  #       git commit -m "Update tag in Helm chart"
  #       git push
