name: BUILD PUSH SCAN AND UPDATE IMAGE FOR CHECKOUT SERVICE

on:
  push:
    branches:
      - main
    paths:
      - 'checkoutservice/**'
      - '.github/workflows/checkout.yaml'
jobs:
  call-build-push-and-scan-cartservice-image:
    uses: ./.github/workflows/build-docker-image.yaml
    with:
      image_name: checkout
      dockerfile_path: checkoutservice/Dockerfile
      context_path: checkoutservice
      tag: ${{ github.run_id }}
      trivy_severity: 'CRITICAL,HIGH'
    secrets:
      GHCR_TOKEN: ${{ secrets.TOKEN }}