name: "Deploy OIDC Role for GitHub Actions"

on:
  push:
    branches:
      - main
    paths:
      - 'oidc-setup/**'
      - '.github/workflows/deploy-oidc.yaml'

permissions:
  id-token: write
  contents: read

jobs:
  deploy-oidc:
    name: "Deploy OIDC IAM Role via Terraform"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: oidc-setup 

    env:
      AWS_REGION: eu-north-1

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform validate
        run: |
            terraform fmt
            terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Output
        run: terraform output
